version: 2.1
jobs:

  deploy:
    working_directory: ~/circle-tmp-folder
    docker:
        - image: cimg/node:18.10.0
    steps:
       - checkout

       - run:
           name: Install aws cli
           command:
             sudo apt-get update && sudo apt-get install python3 python3-pip && sudo pip3 install awscli

       - run:
           name: Setting Signature Version 4 for S3 Request Authentication
           command: aws configure set default.s3.signature_version s3v4

       - run:
           name: awscli1
           command: aws configure set region us-west-2

       - run:
           name: Deploy
           command: 'aws s3 sync ~/circle-tmp-folder s3://rorygibson.me --delete --region eu-west-1  --exclude ".git/*"'

       - run:
           name: awscli1
           command: aws configure set preview.cloudfront true

       - run:
           name: awscli1
           command: aws configure set preview.create-invalidation true

       - run:
           name: CloudFront invalidation
           command: aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E209NN5SKNUFNQ\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          context: rorygibson.me
